import { Contact } from '@/types/contact';

export const tvShows = [
  { id: 'fairy-tales', name: 'Fairy Tales', decade: 'Classic', type: 'literature' },
  { id: 'greek-mythology', name: 'Greek Mythology', decade: 'Ancient', type: 'mythology' },
  { id: 'shakespeare', name: 'Shakespeare', decade: '1600s', type: 'literature' },
  { id: 'alice-wonderland', name: 'Alice in Wonderland', decade: '1865', type: 'literature' },
  { id: 'wizard-of-oz', name: 'Wizard of Oz', decade: '1900', type: 'literature' },
  { id: 'peter-pan', name: 'Peter Pan', decade: '1904', type: 'literature' },
  { id: 'robin-hood', name: 'Robin Hood', decade: 'Medieval', type: 'folklore' },
  { id: 'arabian-nights', name: 'Arabian Nights', decade: 'Classic', type: 'folklore' },
  { id: 'arthurian-legend', name: 'Arthurian Legend', decade: 'Medieval', type: 'folklore' },
  { id: 'grimm-tales', name: 'Grimm Tales', decade: '1812', type: 'literature' },
  { id: 'norse-mythology', name: 'Norse Mythology', decade: 'Ancient', type: 'mythology' },
  { id: 'sherlock-holmes', name: 'Sherlock Holmes', decade: '1887', type: 'literature' },
  { id: 'dracula', name: 'Dracula', decade: '1897', type: 'literature' },
  { id: 'frankenstein', name: 'Frankenstein', decade: '1818', type: 'literature' },
  { id: 'little-women', name: 'Little Women', decade: '1868', type: 'literature' },
  { id: 'pride-prejudice', name: 'Pride and Prejudice', decade: '1813', type: 'literature' },
  { id: 'treasure-island', name: 'Treasure Island', decade: '1883', type: 'literature' },
  { id: 'three-musketeers', name: 'Three Musketeers', decade: '1844', type: 'literature' },
  { id: 'oliver-twist', name: 'Oliver Twist', decade: '1838', type: 'literature' },
  { id: 'tom-sawyer', name: 'Tom Sawyer', decade: '1876', type: 'literature' },
];

export const fictionalContacts: Contact[] = [
  {
    id: 'cinderella',
    firstName: 'Cinderella',
    lastName: '',
    phone: '555-GLASS',
    email: 'cinderella@fairytale.com',
    address: 'Royal Palace',
    birthday: '03/15/1650',
    holidayCard: true,
    notes: 'Lost glass slipper at midnight',
    tvShow: 'Fairy Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'snow-white',
    firstName: 'Snow',
    lastName: 'White',
    phone: '555-APPLE',
    email: 'snow@fairytale.com',
    address: 'Seven Dwarfs Cottage',
    birthday: '12/21/1812',
    holidayCard: true,
    notes: 'Fairest of them all',
    tvShow: 'Fairy Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sleeping-beauty',
    firstName: 'Aurora',
    lastName: '',
    phone: '555-SLEEP',
    email: 'aurora@fairytale.com',
    address: 'Enchanted Castle',
    birthday: '01/29/1697',
    holidayCard: true,
    notes: 'Cursed to sleep for 100 years',
    tvShow: 'Fairy Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'little-red',
    firstName: 'Red',
    lastName: 'Riding Hood',
    phone: '555-WOLF',
    email: 'red@fairytale.com',
    address: "Grandmother's House",
    birthday: '06/12/1697',
    holidayCard: true,
    notes: 'Beware of wolves in the forest',
    tvShow: 'Fairy Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rapunzel',
    firstName: 'Rapunzel',
    lastName: '',
    phone: '555-HAIR',
    email: 'rapunzel@fairytale.com',
    address: 'Tower in the Woods',
    birthday: '05/01/1812',
    holidayCard: true,
    notes: 'Let down your hair!',
    tvShow: 'Fairy Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hansel',
    firstName: 'Hansel',
    lastName: '',
    phone: '555-BREAD',
    email: 'hansel@fairytale.com',
    address: 'Forest Cottage',
    birthday: '08/15/1812',
    holidayCard: true,
    notes: 'Breadcrumb trail expert',
    tvShow: 'Grimm Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'gretel',
    firstName: 'Gretel',
    lastName: '',
    phone: '555-CANDY',
    email: 'gretel@fairytale.com',
    address: 'Forest Cottage',
    birthday: '08/15/1812',
    holidayCard: true,
    notes: 'Outsmarted the witch',
    tvShow: 'Grimm Tales',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'zeus',
    firstName: 'Zeus',
    lastName: '',
    phone: '555-THUNDER',
    email: 'zeus@olympus.gr',
    address: 'Mount Olympus',
    birthday: 'Ancient Times',
    holidayCard: false,
    notes: 'King of the gods, master of lightning',
    tvShow: 'Greek Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'athena',
    firstName: 'Athena',
    lastName: '',
    phone: '555-WISDOM',
    email: 'athena@olympus.gr',
    address: 'Mount Olympus',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Goddess of wisdom and warfare',
    tvShow: 'Greek Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'aphrodite',
    firstName: 'Aphrodite',
    lastName: '',
    phone: '555-LOVE',
    email: 'aphrodite@olympus.gr',
    address: 'Mount Olympus',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Goddess of love and beauty',
    tvShow: 'Greek Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hercules',
    firstName: 'Hercules',
    lastName: '',
    phone: '555-STRONG',
    email: 'hercules@greece.gr',
    address: 'Thebes',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Completed 12 impossible labors',
    tvShow: 'Greek Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'odysseus',
    firstName: 'Odysseus',
    lastName: '',
    phone: '555-VOYAGE',
    email: 'odysseus@ithaca.gr',
    address: 'Ithaca',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Epic journey home from Troy',
    tvShow: 'Greek Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'romeo',
    firstName: 'Romeo',
    lastName: 'Montague',
    phone: '555-LOVE',
    email: 'romeo@verona.it',
    address: 'Verona, Italy',
    birthday: '1597',
    holidayCard: true,
    notes: 'Wherefore art thou?',
    tvShow: 'Shakespeare',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'juliet',
    firstName: 'Juliet',
    lastName: 'Capulet',
    phone: '555-ROSE',
    email: 'juliet@verona.it',
    address: 'Verona, Italy',
    birthday: '1597',
    holidayCard: true,
    notes: 'A rose by any other name',
    tvShow: 'Shakespeare',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hamlet',
    firstName: 'Hamlet',
    lastName: 'Prince of Denmark',
    phone: '555-SKULL',
    email: 'hamlet@elsinore.dk',
    address: 'Elsinore Castle',
    birthday: '1600',
    holidayCard: false,
    notes: 'To be or not to be',
    tvShow: 'Shakespeare',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ophelia',
    firstName: 'Ophelia',
    lastName: '',
    phone: '555-FLOWER',
    email: 'ophelia@elsinore.dk',
    address: 'Elsinore Castle',
    birthday: '1600',
    holidayCard: true,
    notes: 'Tragic heroine',
    tvShow: 'Shakespeare',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'macbeth',
    firstName: 'Macbeth',
    lastName: '',
    phone: '555-KING',
    email: 'macbeth@scotland.uk',
    address: 'Inverness Castle',
    birthday: '1606',
    holidayCard: false,
    notes: 'Beware the witches',
    tvShow: 'Shakespeare',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lady-macbeth',
    firstName: 'Lady',
    lastName: 'Macbeth',
    phone: '555-SPOT',
    email: 'ladymacbeth@scotland.uk',
    address: 'Inverness Castle',
    birthday: '1606',
    holidayCard: false,
    notes: 'Out, damned spot!',
    tvShow: 'Shakespeare',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'alice',
    firstName: 'Alice',
    lastName: '',
    phone: '555-RABBIT',
    email: 'alice@wonderland.com',
    address: 'Down the Rabbit Hole',
    birthday: '11/26/1865',
    holidayCard: true,
    notes: 'Curiouser and curiouser!',
    tvShow: 'Alice in Wonderland',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mad-hatter',
    firstName: 'Mad',
    lastName: 'Hatter',
    phone: '555-TEA',
    email: 'hatter@wonderland.com',
    address: 'Tea Party Table',
    birthday: '11/26/1865',
    holidayCard: true,
    notes: 'Why is a raven like a writing desk?',
    tvShow: 'Alice in Wonderland',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cheshire-cat',
    firstName: 'Cheshire',
    lastName: 'Cat',
    phone: '555-GRIN',
    email: 'cheshire@wonderland.com',
    address: 'Everywhere and Nowhere',
    birthday: '11/26/1865',
    holidayCard: false,
    notes: "We're all mad here",
    tvShow: 'Alice in Wonderland',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'queen-hearts',
    firstName: 'Queen',
    lastName: 'of Hearts',
    phone: '555-OFF',
    email: 'queen@wonderland.com',
    address: 'Royal Palace',
    birthday: '11/26/1865',
    holidayCard: false,
    notes: 'Off with their heads!',
    tvShow: 'Alice in Wonderland',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dorothy-gale',
    firstName: 'Dorothy',
    lastName: 'Gale',
    phone: '555-KANSAS',
    email: 'dorothy@oz.com',
    address: 'Kansas Farm',
    birthday: '05/17/1900',
    holidayCard: true,
    notes: "There's no place like home",
    tvShow: 'Wizard of Oz',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'scarecrow',
    firstName: 'Scarecrow',
    lastName: '',
    phone: '555-BRAIN',
    email: 'scarecrow@oz.com',
    address: 'Yellow Brick Road',
    birthday: '05/17/1900',
    holidayCard: true,
    notes: 'If I only had a brain',
    tvShow: 'Wizard of Oz',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tin-man',
    firstName: 'Tin',
    lastName: 'Man',
    phone: '555-HEART',
    email: 'tinman@oz.com',
    address: 'Yellow Brick Road',
    birthday: '05/17/1900',
    holidayCard: true,
    notes: 'If I only had a heart',
    tvShow: 'Wizard of Oz',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'cowardly-lion',
    firstName: 'Cowardly',
    lastName: 'Lion',
    phone: '555-COURAGE',
    email: 'lion@oz.com',
    address: 'Yellow Brick Road',
    birthday: '05/17/1900',
    holidayCard: true,
    notes: 'If I only had courage',
    tvShow: 'Wizard of Oz',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'peter-pan',
    firstName: 'Peter',
    lastName: 'Pan',
    phone: '555-FLY',
    email: 'peter@neverland.com',
    address: 'Neverland',
    birthday: '12/27/1904',
    holidayCard: true,
    notes: 'The boy who never grew up',
    tvShow: 'Peter Pan',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tinker-bell',
    firstName: 'Tinker',
    lastName: 'Bell',
    phone: '555-PIXIE',
    email: 'tinkerbell@neverland.com',
    address: 'Neverland',
    birthday: '12/27/1904',
    holidayCard: true,
    notes: 'Fairy dust and attitude',
    tvShow: 'Peter Pan',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'wendy-darling',
    firstName: 'Wendy',
    lastName: 'Darling',
    phone: '555-STORY',
    email: 'wendy@london.uk',
    address: 'London',
    birthday: '12/27/1904',
    holidayCard: true,
    notes: 'Mother to the Lost Boys',
    tvShow: 'Peter Pan',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'captain-hook',
    firstName: 'Captain',
    lastName: 'Hook',
    phone: '555-CROC',
    email: 'hook@neverland.com',
    address: 'Jolly Roger Ship',
    birthday: '12/27/1904',
    holidayCard: false,
    notes: 'Beware the crocodile',
    tvShow: 'Peter Pan',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'robin-hood',
    firstName: 'Robin',
    lastName: 'Hood',
    phone: '555-ARROW',
    email: 'robin@sherwood.uk',
    address: 'Sherwood Forest',
    birthday: '1200',
    holidayCard: true,
    notes: 'Steals from rich, gives to poor',
    tvShow: 'Robin Hood',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'maid-marian',
    firstName: 'Maid',
    lastName: 'Marian',
    phone: '555-FAIR',
    email: 'marian@nottingham.uk',
    address: 'Nottingham',
    birthday: '1200',
    holidayCard: true,
    notes: "Robin's true love",
    tvShow: 'Robin Hood',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'little-john',
    firstName: 'Little',
    lastName: 'John',
    phone: '555-BIG',
    email: 'littlejohn@sherwood.uk',
    address: 'Sherwood Forest',
    birthday: '1200',
    holidayCard: true,
    notes: "Robin's right-hand man",
    tvShow: 'Robin Hood',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'friar-tuck',
    firstName: 'Friar',
    lastName: 'Tuck',
    phone: '555-MONK',
    email: 'tuck@sherwood.uk',
    address: 'Sherwood Forest',
    birthday: '1200',
    holidayCard: true,
    notes: 'Jolly friar and fighter',
    tvShow: 'Robin Hood',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'aladdin',
    firstName: 'Aladdin',
    lastName: '',
    phone: '555-LAMP',
    email: 'aladdin@arabia.com',
    address: 'Agrabah',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Found the magic lamp',
    tvShow: 'Arabian Nights',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'scheherazade',
    firstName: 'Scheherazade',
    lastName: '',
    phone: '555-STORY',
    email: 'scheherazade@arabia.com',
    address: 'Palace',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: '1001 nights of stories',
    tvShow: 'Arabian Nights',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sinbad',
    firstName: 'Sinbad',
    lastName: 'the Sailor',
    phone: '555-VOYAGE',
    email: 'sinbad@arabia.com',
    address: 'The Seven Seas',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Seven legendary voyages',
    tvShow: 'Arabian Nights',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ali-baba',
    firstName: 'Ali',
    lastName: 'Baba',
    phone: '555-CAVE',
    email: 'alibaba@arabia.com',
    address: 'Baghdad',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Open sesame!',
    tvShow: 'Arabian Nights',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'king-arthur',
    firstName: 'King',
    lastName: 'Arthur',
    phone: '555-SWORD',
    email: 'arthur@camelot.uk',
    address: 'Camelot',
    birthday: '500 AD',
    holidayCard: true,
    notes: 'Pulled sword from stone',
    tvShow: 'Arthurian Legend',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'guinevere',
    firstName: 'Guinevere',
    lastName: '',
    phone: '555-QUEEN',
    email: 'guinevere@camelot.uk',
    address: 'Camelot',
    birthday: '500 AD',
    holidayCard: true,
    notes: 'Queen of Camelot',
    tvShow: 'Arthurian Legend',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lancelot',
    firstName: 'Sir',
    lastName: 'Lancelot',
    phone: '555-KNIGHT',
    email: 'lancelot@camelot.uk',
    address: 'Camelot',
    birthday: '500 AD',
    holidayCard: true,
    notes: 'Bravest knight of the Round Table',
    tvShow: 'Arthurian Legend',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'merlin',
    firstName: 'Merlin',
    lastName: '',
    phone: '555-MAGIC',
    email: 'merlin@camelot.uk',
    address: 'Camelot',
    birthday: '500 AD',
    holidayCard: true,
    notes: 'Wise wizard and advisor',
    tvShow: 'Arthurian Legend',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'thor',
    firstName: 'Thor',
    lastName: '',
    phone: '555-HAMMER',
    email: 'thor@asgard.no',
    address: 'Asgard',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'God of thunder, wields Mjolnir',
    tvShow: 'Norse Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'odin',
    firstName: 'Odin',
    lastName: '',
    phone: '555-WISE',
    email: 'odin@asgard.no',
    address: 'Asgard',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'All-father, king of the gods',
    tvShow: 'Norse Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'loki',
    firstName: 'Loki',
    lastName: '',
    phone: '555-TRICK',
    email: 'loki@asgard.no',
    address: 'Asgard',
    birthday: 'Ancient Times',
    holidayCard: false,
    notes: 'Trickster god',
    tvShow: 'Norse Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'freya',
    firstName: 'Freya',
    lastName: '',
    phone: '555-LOVE',
    email: 'freya@asgard.no',
    address: 'Asgard',
    birthday: 'Ancient Times',
    holidayCard: true,
    notes: 'Goddess of love and war',
    tvShow: 'Norse Mythology',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'sherlock-holmes',
    firstName: 'Sherlock',
    lastName: 'Holmes',
    phone: '555-CLUE',
    email: 'sherlock@bakerstreet.uk',
    address: '221B Baker Street, London',
    birthday: '01/06/1854',
    holidayCard: false,
    notes: 'Elementary, my dear Watson',
    tvShow: 'Sherlock Holmes',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dr-watson',
    firstName: 'Dr. John',
    lastName: 'Watson',
    phone: '555-DOC',
    email: 'watson@bakerstreet.uk',
    address: '221B Baker Street, London',
    birthday: '07/07/1852',
    holidayCard: true,
    notes: "Holmes' faithful companion",
    tvShow: 'Sherlock Holmes',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'irene-adler',
    firstName: 'Irene',
    lastName: 'Adler',
    phone: '555-WOMAN',
    email: 'irene@london.uk',
    address: 'London',
    birthday: '1858',
    holidayCard: true,
    notes: 'The Woman who outwitted Holmes',
    tvShow: 'Sherlock Holmes',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'count-dracula',
    firstName: 'Count',
    lastName: 'Dracula',
    phone: '555-BITE',
    email: 'dracula@transylvania.ro',
    address: 'Castle Dracula, Transylvania',
    birthday: '1431',
    holidayCard: false,
    notes: 'I vant to suck your blood',
    tvShow: 'Dracula',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mina-harker',
    firstName: 'Mina',
    lastName: 'Harker',
    phone: '555-BRAVE',
    email: 'mina@london.uk',
    address: 'London',
    birthday: '1872',
    holidayCard: true,
    notes: 'Brave heroine',
    tvShow: 'Dracula',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'van-helsing',
    firstName: 'Abraham',
    lastName: 'Van Helsing',
    phone: '555-HUNT',
    email: 'vanhelsing@amsterdam.nl',
    address: 'Amsterdam',
    birthday: '1840',
    holidayCard: true,
    notes: 'Vampire hunter extraordinaire',
    tvShow: 'Dracula',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'victor-frankenstein',
    firstName: 'Victor',
    lastName: 'Frankenstein',
    phone: '555-LIFE',
    email: 'victor@geneva.ch',
    address: 'Geneva, Switzerland',
    birthday: '1797',
    holidayCard: false,
    notes: 'Created life from death',
    tvShow: 'Frankenstein',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'frankenstein-creature',
    firstName: 'The',
    lastName: 'Creature',
    phone: '555-ALONE',
    email: 'creature@arctic.com',
    address: 'The Arctic',
    birthday: '1818',
    holidayCard: true,
    notes: 'Misunderstood creation',
    tvShow: 'Frankenstein',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'jo-march',
    firstName: 'Jo',
    lastName: 'March',
    phone: '555-WRITE',
    email: 'jo@concord.ma',
    address: 'Concord, Massachusetts',
    birthday: '11/29/1832',
    holidayCard: true,
    notes: 'Aspiring writer, independent spirit',
    tvShow: 'Little Women',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'meg-march',
    firstName: 'Meg',
    lastName: 'March',
    phone: '555-ELDEST',
    email: 'meg@concord.ma',
    address: 'Concord, Massachusetts',
    birthday: '1832',
    holidayCard: true,
    notes: 'Eldest sister, dreams of family',
    tvShow: 'Little Women',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'beth-march',
    firstName: 'Beth',
    lastName: 'March',
    phone: '555-PIANO',
    email: 'beth@concord.ma',
    address: 'Concord, Massachusetts',
    birthday: '1835',
    holidayCard: true,
    notes: 'Gentle soul, loves music',
    tvShow: 'Little Women',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'amy-march',
    firstName: 'Amy',
    lastName: 'March',
    phone: '555-ART',
    email: 'amy@concord.ma',
    address: 'Concord, Massachusetts',
    birthday: '1837',
    holidayCard: true,
    notes: 'Youngest sister, aspiring artist',
    tvShow: 'Little Women',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'elizabeth-bennet',
    firstName: 'Elizabeth',
    lastName: 'Bennet',
    phone: '555-PRIDE',
    email: 'lizzy@longbourn.uk',
    address: 'Longbourn, England',
    birthday: '1797',
    holidayCard: true,
    notes: 'Witty and independent',
    tvShow: 'Pride and Prejudice',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mr-darcy',
    firstName: 'Fitzwilliam',
    lastName: 'Darcy',
    phone: '555-PEMBERLEY',
    email: 'darcy@pemberley.uk',
    address: 'Pemberley Estate',
    birthday: '1787',
    holidayCard: true,
    notes: 'Proud but honorable gentleman',
    tvShow: 'Pride and Prejudice',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'jane-bennet',
    firstName: 'Jane',
    lastName: 'Bennet',
    phone: '555-SWEET',
    email: 'jane@longbourn.uk',
    address: 'Longbourn, England',
    birthday: '1795',
    holidayCard: true,
    notes: 'Eldest Bennet sister, kind heart',
    tvShow: 'Pride and Prejudice',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'jim-hawkins',
    firstName: 'Jim',
    lastName: 'Hawkins',
    phone: '555-CABIN',
    email: 'jim@treasure.com',
    address: 'Admiral Benbow Inn',
    birthday: '1750',
    holidayCard: true,
    notes: 'Brave cabin boy',
    tvShow: 'Treasure Island',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'long-john-silver',
    firstName: 'Long John',
    lastName: 'Silver',
    phone: '555-PARROT',
    email: 'silver@treasure.com',
    address: 'The Hispaniola',
    birthday: '1720',
    holidayCard: false,
    notes: 'One-legged pirate cook',
    tvShow: 'Treasure Island',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'captain-smollett',
    firstName: 'Captain',
    lastName: 'Smollett',
    phone: '555-SHIP',
    email: 'smollett@treasure.com',
    address: 'The Hispaniola',
    birthday: '1730',
    holidayCard: true,
    notes: 'Honorable ship captain',
    tvShow: 'Treasure Island',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'athos',
    firstName: 'Athos',
    lastName: '',
    phone: '555-SWORD1',
    email: 'athos@musketeers.fr',
    address: 'Paris, France',
    birthday: '1625',
    holidayCard: true,
    notes: 'Noble and wise musketeer',
    tvShow: 'Three Musketeers',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'porthos',
    firstName: 'Porthos',
    lastName: '',
    phone: '555-SWORD2',
    email: 'porthos@musketeers.fr',
    address: 'Paris, France',
    birthday: '1625',
    holidayCard: true,
    notes: 'Strong and vain musketeer',
    tvShow: 'Three Musketeers',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'aramis',
    firstName: 'Aramis',
    lastName: '',
    phone: '555-SWORD3',
    email: 'aramis@musketeers.fr',
    address: 'Paris, France',
    birthday: '1625',
    holidayCard: true,
    notes: 'Romantic musketeer',
    tvShow: 'Three Musketeers',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'dartagnan',
    firstName: "D'Artagnan",
    lastName: '',
    phone: '555-YOUNG',
    email: 'dartagnan@musketeers.fr',
    address: 'Paris, France',
    birthday: '1625',
    holidayCard: true,
    notes: 'All for one, one for all!',
    tvShow: 'Three Musketeers',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'oliver-twist',
    firstName: 'Oliver',
    lastName: 'Twist',
    phone: '555-MORE',
    email: 'oliver@london.uk',
    address: 'London Workhouse',
    birthday: '1838',
    holidayCard: true,
    notes: 'Please sir, I want some more',
    tvShow: 'Oliver Twist',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'artful-dodger',
    firstName: 'Artful',
    lastName: 'Dodger',
    phone: '555-PICK',
    email: 'dodger@london.uk',
    address: 'London Streets',
    birthday: '1838',
    holidayCard: false,
    notes: 'Skilled pickpocket',
    tvShow: 'Oliver Twist',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'fagin',
    firstName: 'Fagin',
    lastName: '',
    phone: '555-FENCE',
    email: 'fagin@london.uk',
    address: 'London Den',
    birthday: '1800',
    holidayCard: false,
    notes: 'Leader of child thieves',
    tvShow: 'Oliver Twist',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tom-sawyer',
    firstName: 'Tom',
    lastName: 'Sawyer',
    phone: '555-FENCE',
    email: 'tom@stpetersburg.mo',
    address: 'St. Petersburg, Missouri',
    birthday: '1844',
    holidayCard: true,
    notes: 'Mischievous boy with big imagination',
    tvShow: 'Tom Sawyer',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'huck-finn',
    firstName: 'Huckleberry',
    lastName: 'Finn',
    phone: '555-RAFT',
    email: 'huck@stpetersburg.mo',
    address: 'St. Petersburg, Missouri',
    birthday: '1844',
    holidayCard: true,
    notes: "Tom's best friend, free spirit",
    tvShow: 'Tom Sawyer',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'becky-thatcher',
    firstName: 'Becky',
    lastName: 'Thatcher',
    phone: '555-SCHOOL',
    email: 'becky@stpetersburg.mo',
    address: 'St. Petersburg, Missouri',
    birthday: '1844',
    holidayCard: true,
    notes: "Tom's sweetheart",
    tvShow: 'Tom Sawyer',
    isFictional: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
